name: "Teste de orkflow 01x"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'Onde fazer o deploy?'
        required: true
        default: 'homologacao'

jobs:
  job1:
    name: "Job de Teste 01"
    runs-on: ubuntu-latest

    steps:
      - name: "Exibir mensagem de teste"
        run: |
          echo "Este é um teste de workflow"
          ls -la
          echo "Ambiente selecionado: ${{ github.event.inputs.ambiente }}"

  job2:
    name: "Job de Teste 02"
    runs-on: ubuntu-latest
    needs: job1  # O job2 só executa após o job1 concluir

    steps:
      - name: "Mensagem após o Job 1"
        run: |
          echo "Job 2 executado após o Job 1"
          echo "Deploy no ambiente: ${{ github.event.inputs.ambiente }}"
          ls -la
